import = ["~/.config/alacritty/themes/tokyonight.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
padding.x = 20
padding.y = 24
decorations = "Transparent"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 13
